# Generated by Django 5.0.3 on 2024-03-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(verbose_name='Nitrogen Content (ppm)')),
                ('p', models.FloatField(verbose_name='Phosphorus Content (ppm)')),
                ('k', models.FloatField(verbose_name='Potassium Content (ppm)')),
                ('temperature', models.FloatField(verbose_name='Average Annual Temperature (°C)')),
                ('humidity', models.FloatField(verbose_name='Average Annual Humidity (%)')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='Soil pH')),
                ('rainfall', models.FloatField(blank=True, null=True, verbose_name='Average Annual Rainfall (mm)')),
                ('recommended_crop', models.CharField(max_length=255, verbose_name='Recommended Crop')),
            ],
        ),
    ]
