from django import forms

class InputForm(forms.Form):
    
    # Define choices for the crop (item) field
    CROP_CHOICES = [
        ('0', 'Cassava'),
        ('1', 'Maize'),
        ('2', 'Plantains and others'),
        ('3', 'Potatoes'),
        ('4', 'Rice, paddy'),
        ('5', 'Sorghum'),
        ('6', 'Soybeans'),
        ('7', 'Sweet potatoes'),
        ('8', 'Wheat'),
        ('9', 'Yams'),
    ]
    
    # Define choices for the area field (countries)
   
    AREA_CHOICES = [
        ('0', 'Algeria'), ('1', 'Angola'), ('2', 'Argentina'), ('3', 'Australia'), ('4', 'Azerbaijan'),
        ('5', 'Bangladesh'), ('6', 'Brazil'), ('7', 'Bulgaria'), ('8', 'Burkina Faso'), ('9', 'Burundi'),
        ('10', 'Cameroon'), ('11', 'Canada'), ('12', 'Central African Republic'), ('13', 'Chile'),
        ('14', 'Colombia'), ('15', 'Croatia'), ('16', 'Dominican Republic'), ('17', 'Ecuador'),
        ('18', 'Egypt'), ('19', 'El Salvador'), ('20', 'France'), ('21', 'Germany'), ('22', 'Ghana'),
        ('23', 'Greece'), ('24', 'Guatemala'), ('25', 'Guinea'), ('26', 'Guyana'), ('27', 'Haiti'),
        ('28', 'Honduras'), ('29', 'Hungary'), ('30', 'India'), ('31', 'Indonesia'), ('32', 'Iraq'),
        ('33', 'Italy'), ('34', 'Jamaica'), ('35', 'Japan'), ('36', 'Kazakhstan'), ('37', 'Kenya'),
        ('38', 'Libya'), ('39', 'Madagascar'), ('40', 'Malawi'), ('41', 'Mali'), ('42', 'Mauritania'),
        ('43', 'Mauritius'), ('44', 'Mexico'), ('45', 'Morocco'), ('46', 'Mozambique'), ('47', 'Nepal'),
        ('48', 'Nicaragua'), ('49', 'Niger'), ('50', 'Pakistan'), ('51', 'Papua New Guinea'),
        ('52', 'Peru'), ('53', 'Portugal'), ('54', 'Romania'), ('55', 'Rwanda'), ('56', 'Saudi Arabia'),
        ('57', 'Senegal'), ('58', 'South Africa'), ('59', 'Spain'), ('60', 'Sri Lanka'),
        ('61', 'Suriname'), ('62', 'Tajikistan'), ('63', 'Thailand'), ('64', 'Turkey'), ('65', 'Uganda'),
        ('66', 'Ukraine'), ('67', 'United Kingdom'), ('68', 'Uruguay'), ('69', 'Zambia'),
        ('70', 'Zimbabwe'),
      ]

    
    YEAR_CHOICES = [(year, year) for year in range(1990, 2051)]
    
    area = forms.ChoiceField(label='Area', choices=AREA_CHOICES)
    item = forms.ChoiceField(label='Crop', choices=CROP_CHOICES)
    year = forms.ChoiceField(label='Year', choices=YEAR_CHOICES)
    average_rain_fall_mm_per_year = forms.FloatField(label='Average Rain Fall (mm per year)')
    pesticides_tonnes = forms.FloatField(label='Pesticides (tonnes)')
    avg_temp = forms.FloatField(label='Average Temperature')




#with 101 countries model
 # AREA_CHOICES = [
    #     ('0', 'Albania'),
    #     ('1', 'Algeria'),
    #     ('2', 'Angola'),
    #     ('3', 'Argentina'),
    #     ('4', 'Armenia'),
    #     ('5', 'Australia'),
    #     ('6', 'Austria'),
    #     ('7', 'Azerbaijan'),
    #     ('8', 'Bahamas'),
    #     ('9', 'Bahrain'),
    #     ('10', 'Bangladesh'),
    #     ('11', 'Belarus'),
    #     ('12', 'Belgium'),
    #     ('13', 'Botswana'),
    #     ('14', 'Brazil'),
    #     ('15', 'Bulgaria'),
    #     ('16', 'Burkina Faso'),
    #     ('17', 'Burundi'),
    #     ('18', 'Cameroon'),
    #     ('19', 'Canada'),
    #     ('20', 'Central African Republic'),
    #     ('21', 'Chile'),
    #     ('22', 'Colombia'),
    #     ('23', 'Croatia'),
    #     ('24', 'Denmark'),
    #     ('25', 'Dominican Republic'),
    #     ('26', 'Ecuador'),
    #     ('27', 'Egypt'),
    #     ('28', 'El Salvador'),
    #     ('29', 'Eritrea'),
    #     ('30', 'Estonia'),
    #     ('31', 'Finland'),
    #     ('32', 'France'),
    #     ('33', 'Germany'),
    #     ('34', 'Ghana'),
    #     ('35', 'Greece'),
    #     ('36', 'Guatemala'),
    #     ('37', 'Guinea'),
    #     ('38', 'Guyana'),
    #     ('39', 'Haiti'),
    #     ('40', 'Honduras'),
    #     ('41', 'Hungary'),
    #     ('42', 'India'),
    #     ('43', 'Indonesia'),
    #     ('44', 'Iraq'),
    #     ('45', 'Ireland'),
    #     ('46', 'Italy'),
    #     ('47', 'Jamaica'),
    #     ('48', 'Japan'),
    #     ('49', 'Kazakhstan'),
    #     ('50', 'Kenya'),
    #     ('51', 'Latvia'),
    #     ('52', 'Lebanon'),
    #     ('53', 'Lesotho'),
    #     ('54', 'Libya'),
    #     ('55', 'Lithuania'),
    #     ('56', 'Madagascar'),
    #     ('57', 'Malawi'),
    #     ('58', 'Malaysia'),
    #     ('59', 'Mali'),
    #     ('60', 'Mauritania'),
    #     ('61', 'Mauritius'),
    #     ('62', 'Mexico'),
    #     ('63', 'Montenegro'),
    #     ('64', 'Morocco'),
    #     ('65', 'Mozambique'),
    #     ('66', 'Namibia'),
    #     ('67', 'Nepal'),
    #     ('68', 'Netherlands'),
    #     ('69', 'New Zealand'),
    #     ('70', 'Nicaragua'),
    #     ('71', 'Niger'),
    #     ('72', 'Norway'),
    #     ('73', 'Pakistan'),
    #     ('74', 'Papua New Guinea'),
    #     ('75', 'Peru'),
    #     ('76', 'Poland'),
    #     ('77', 'Portugal'),
    #     ('78', 'Qatar'),
    #     ('79', 'Romania'),
    #     ('80', 'Rwanda'),
    #     ('81', 'Saudi Arabia'),
    #     ('82', 'Senegal'),
    #     ('83', 'Slovenia'),
    #     ('84', 'South Africa'),
    #     ('85', 'Spain'),
    #     ('86', 'Sri Lanka'),
    #     ('87', 'Sudan'),
    #     ('88', 'Suriname'),
    #     ('89', 'Sweden'),
    #     ('90', 'Switzerland'),
    #     ('91', 'Tajikistan'),
    #     ('92', 'Thailand'),
    #     ('93', 'Tunisia'),
    #     ('94', 'Turkey'),
    #     ('95', 'Uganda'),
    #     ('96', 'Ukraine'),
    #     ('97', 'United Kingdom'),
    #     ('98', 'Uruguay'),
    #     ('99', 'Zambia'),
    #     ('100', 'Zimbabwe'),
    # ]
